detectives:
  - id: 3
    rtmp:
      pull_stream: https://cn-jsyz-ct-03-27.bilivideo.com/live-bvc/949839/live_3494368669338503_7711584_1500/index.m3u8
      push_stream: rtmp://localhost/live/livestream123
      play_url: http://localhost:8080/live/livestream123.flv
    monitoring_topics:
      - person
      - fire
    polygon_coordinates:
      - null
  - id: 12
    rtmp:
      pull_stream: rtmp://localhost/live/livestream2
      push_stream: rtmp://localhost/live/livestream321
      play_url: http://localhost:8080/live/livestream321.flv
    monitoring_topics:
      - person
      - fire
      - smoke
    polygon_coordinates:
      - [100, 100]
      - [200, 50]
      - [2500, 100]
      - [2150, 200]
      - [2200, 2200]

yolo:
  models: 
    - name: yolov5m #模型名 
      repo_or_dir: ultralytics/yolov5 #模型路径/库 
    - name: ./fire_smoke.pt #模型名 
  refresh_time_ms: 0  # YOLO模型的刷新时间，单位为毫秒
  show_detected_line: True #探测的需要报警的物体才显示框,否则探测到的所有物体都显示框。

pull_rtmp: 
  long_wait_retry_seconds: 10 #最长rtmp重试时间
  short_wait_retry_seconds: 4 #最短rtmp重试时间
  number_of_retry_short2long: 111 #最短到最长的切换次数
  daemon: False #拉流是否守护子线程
  cache_size: 10240 #拉流缓冲区frame存放数量 超过就丢弃

server:
  check_config_second: 3 #检查配置间隔时间